apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: lectern-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: lectern-basic-auth
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  tls:
    - hosts:
      - qa.cqdg.ferlab.bio
      secretName: letsencrypt-certificate
  rules:
    - host: qa.cqdg.ferlab.bio
      http:
        paths:
        - path: /
          backend:
            serviceName: lectern
            servicePort: 3000