apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cqdg-qa

resources:
  - ../../cqdg-orchestrations/datagrid-service
  - migrations
  - ingresses.yml

patchesStrategicMerge:
  - deployments-overrides.yml
  - postgres-override.yml

configMapGenerator:
  - name: datagrid-service-customizations
    options:
      disableNameSuffixHash: false
    literals:
      - SAVE_SETS_FILE_TYPE=savesets_file
      - SAVE_SETS_DONOR_TYPE=savesets_donor
      - SQON_QUERY_TYPE=sqon
  - name: datagrid-service-keycloak-access
    options:
      disableNameSuffixHash: false
    literals:
      - AUTH_CLIENT_ID=cqdg-client
      - AUTH_SERVER_URL=https://auth.qa.cqdg.ferlab.bio/auth
      - AUTH_REALM=CQDG